/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    NormalNavBar: typeof import('./src/components/NormalNavBar.vue')['default']
    Page: typeof import('./src/components/Atom/Page.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
}
